# Generated by Django 2.2.12 on 2020-04-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200425_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order', 
            name='tag',
            field=models.ManyToManyField(to='account.Tag'),
        ),
    ]
